-- insert values into Student
insert into Student values ('Kevin', 'ÄÐ', 30, '1980-2-1')
insert into Student values ('Amy', 'Å®', 15, '2000-5-7')
insert into Student values ('Joe', 'ÄÐ', 28, '1982-4-23')
insert into Student values ('Grace', 'Å®', 30, '1980-9-27')
insert into Student values ('Annie', 'Å®', 30, '1980-12-15')
insert into Student values ('Jane', 'Å®', 12, '2003-3-6')
insert into Student values ('Mike', 'ÄÐ', 7, '2005-5-19')
insert into Student values ('Cathy', 'Å®', 40, '1970-1-2')
insert into Student values ('Lee', 'ÄÐ', 60, '1950-6-7')
insert into Student values ('Brown', 'ÄÐ', 80, '1940-5-1')

--insert values into Teacher
insert into Teacher values ('Li Ming', 'ÄÐ', 6)
insert into Teacher values ('Han Mei Mei', 'Å®', 20)
insert into Teacher values ('Zhang Yu', 'Å®', 1)
insert into Teacher values ('Zhang Shujing', 'Å®', 0)
insert into Teacher values ('Liu Yating', 'Å®', 10)
insert into Teacher values ('Han Han', 'ÄÐ', 4)
insert into Teacher values ('Yu Kewei', 'Å®', 3)
insert into Teacher values ('Li Xue', 'Å®', 5)
insert into Teacher values ('Chen Ziang', 'ÄÐ', 7)
insert into Teacher values ('Xue Mingli', 'ÄÐ', 1)
insert into Teacher values ('Ke Libing', 'ÄÐ', 10)
insert into Teacher values ('Wang Xuebing', 'ÄÐ', 11)

insert into Teacher values ('Li Ming', 'ÄÐ', 6)
insert into Teacher values ('Li Ming', 'ÄÐ', 6)
insert into Teacher values ('Li Ming', 'ÄÐ', 6)
insert into Teacher values ('Li Ming', 'ÄÐ', 6)

--insert values into Course
insert into Course values ('Machine learning', 1)
insert into Course values ('Data Science', 4)
insert into Course values ('Data Structure', 6)
insert into Course values ('Introduction to Artificial Intelligence', 6)
insert into Course values ('Database management', 3)
insert into Course values ('Computer Network', 10)
insert into Course values ('Graph Algorithm', 11)
insert into Course values ('Computer Graphics', 15)

--insert values into Grade
insert into Grade values (1,1,80)
insert into Grade values (1,2,10)
insert into Grade values (1,3,40)
insert into Grade values (1,4,30)
insert into Grade values (1,5,66)
insert into Grade values (1,6,90)
insert into Grade values (1,7,10)
insert into Grade values (1,8,15)

insert into Grade values (2,1,30)
insert into Grade values (2,2,70)
insert into Grade values (2,3,60)
insert into Grade values (2,4,54)
insert into Grade values (2,5,65)
insert into Grade values (2,6,34)
insert into Grade values (2,7,99)
insert into Grade values (2,8,45)

insert into Grade values (3,1,90)
insert into Grade values (3,2,99)
insert into Grade values (3,3,91)
insert into Grade values (3,4,60)
insert into Grade values (3,5,82)
insert into Grade values (3,6,43)
insert into Grade values (3,7,100)
insert into Grade values (3,8,70)